### ISSUE TITLE
Additional '/' in server url fails the upload

### ISSUE THREAD

**Issue by amit1agrawal** [pfefferf/grunt-nwabap-ui5uploader#10]
Hi Florian,
Today, I was trying a different server and by mistake I had appended additional '/' in end of the server URL like "http://hostname:port/". This caused an error "Fatal error: No XML to parse!" . I was flabbergasted as the same stuff worked fine in different server. So I used the --debug option to figure out where the error was happening and then I looked into the source code to figure out why the GET request was failing. Constructed the URL manually as would happen in source code and then found out that I had added additional '/'. My bad :(
However, I would recommended to add a note in the documentation or provide more detailed log in verbose mode so that others can figure out such stupid mistake easily. Thanks.

**Comment by pfefferf** [comment]
Not an issue, but a feature request.

**Comment by pfefferf** [comment]
With the latest release (0.1.16) I added some logic to ignore such wrong characters at the end of the server URL.

**Comment by amit1agrawal** [comment]
Great! Thanks.
