### ISSUE TITLE
socket hang up

### ISSUE THREAD

**Issue by impnguyen** [pfefferf/grunt-nwabap-ui5uploader#11]
Hi, 

I tried to upload my build sources, but I got this error: 

```
Running "nwabap_ui5uploader:upload_build" (nwabap_ui5uploader) task
Warning: Error: socket hang up (undefined) Used --force, continuing.
```

Any idea?

best regards

**Comment by pfefferf** [comment]
W/o further information, not really.

**Comment by impnguyen** [comment]
That is my config: 

`				nwabap_ui5uploader : {
					options : {
						conn : {
							server : '<%= ned.ip %>:<%= ned.port %>',
						},
						auth : {
							user :sUser, //'<%= ned.user%>',
							pwd : sPwd//'<%= ned.pw %>'
						}
					},
					upload_build : {
						options : {
							ui5 : {
								package : '<%= ned.package%>',
								//package: '$TMP',
								bspcontainer : '<%= ned.bsp_cont %>',
								bspcontainer_text : '<%= ned.bsp_text %>',
								transportno : '<%= ned.trans_no%>'
							},
							resources : {
								cwd : '<%= dir.build %>',
								src : '**/*.*'
							}
						}
					}
				}`

**Comment by pfefferf** [comment]
Looks ok, can you execute the uploader using "--verbose" to check if you get more information (e.g. if you get to the place where the artifacts to be uploaded are logged).

**Comment by impnguyen** [comment]
Running "nwabap_ui5uploader:upload_build" (nwabap_ui5uploader) task
Verifying property nwabap_ui5uploader.upload_build exists in config...OK
File: [no files]
Options: resources={"cwd":"build/","src":"**/*.*"}, conn={"server":"http://****:****"}, auth={"user":"*****","pwd":"*****"}, ui5={"package":"/***/KAWVF_UI5
_PORTAL","bspcontainer":"/***/VFPORTAL","bspcontainer_text":"Portal für UI5"
,"transportno":" ****"}
Options: {"resources":{"cwd":"build/","src":"**/*.*"},"conn":{"server":"http://****:****","useStrictSSL":true},"auth":{"user":"****","pwd":"****"},"ui5":
{"package":"/***/KAWVF_UI5_PORTAL","bspcontainer":"/***/VFPORTAL","bspcontainer_text":"
Portal für UI5","transportno":" ****","language":"EN"}}
Files:
Warning: Error: socket hang up (undefined) Use --force to continue.

Aborted due to warnings.

=>File: [no files] ... hm

**Comment by impnguyen** [comment]
I built the sources folder. Now it found a lot of files, but I have the same error.

**Comment by pfefferf** [comment]
As you don't get any information about the artifacts to be uploaded (which is in fact a result of the comparision of possible existing files and the local files) it seems that no connection can be made to your NW. Have you ensured that the ADT endpoints are reachable?

**Comment by impnguyen** [comment]
Yes, I can deploy with the default eclipse abap plugin to my nw.

**Comment by impnguyen** [comment]
![image](https://cloud.githubusercontent.com/assets/2463861/20894965/d088c832-bb17-11e6-8cff-9957815897fb.png)

Do I need special permissions ?

**Comment by pfefferf** [comment]
Of course you need the developer rights as described in the ADT guide. That one you should is not one of them.

**Comment by impnguyen** [comment]
I checked my permission roles. I have all necessary objects: s_adt_res, s_rfc, s_tcode

**Comment by pfefferf** [comment]
Cannot be reproduced on my side.

**Comment by ffleige** [comment]
> Options: resources={"cwd":"build/","src":"/."}, **conn={"server":"http://:"}**, auth={"user":"","pwd":""},  ...

@impnguyen: Looks to me as if your grunt variables `ned.ip` and `ned.port` are not set. So the plugin tries to connect to server `http://:` what naturally will fail.

**Comment by impnguyen** [comment]
I deleted the output before posting. This should not be public =)

**Comment by impnguyen** [comment]
Where can I get the port? Maybe it is the wrong port

**Comment by pfefferf** [comment]
Transaction SMICM (https://help.sap.com/saphelp_nw75/helpdata/en/48/89f3ee33b11b5ae10000000a42189c/content.htm?frameset=/de/48/8980e533b11b5ae10000000a42189c/frameset.htm&current_toc=/de/f9/b6a344af114f95943d2d3c1c2a5692/plain.htm&node_id=15)

**Comment by impnguyen** [comment]
Perfect. Now it works! Thanks.
