### ISSUE TITLE
When uploading changes don't seem to be in the application

### ISSUE THREAD

**Issue by rpanneel** [pfefferf/grunt-nwabap-ui5uploader#14]
Hello,

When using the grunt task for deploying the UI5 application i see my changes coming into the controller.js for example in SE80. But when i refresh my app in chrome (with developer tools open and the setting ignore cache on) I still see my old code.

If I use the report /UI5/UI5_REPOSITORY_LOAD and upload my dist-folder I directly see my changes in my app after refreshing. 

Have you ever had this problem? And is there maybe a setting to force this?

Thanks in advance!

Kind regards,

Robin

**Comment by pfefferf** [comment]
Have you used the "calc_appindex" option to recalculate the app index incl. cache-buster infos?

**Comment by rpanneel** [comment]
Indeed i forgot to add the "calc_appindex" option. Tested it with the option and now I directly see my changes! Works like a charm, thanks!
