### ISSUE TITLE
[Feature] Delta Sync

### ISSUE THREAD

**Issue by themasch** [pfefferf/grunt-nwabap-ui5uploader#16]
Hi, 

I'd like to know if you think a delta sync would be a useful and "doable" feature. 
The atom feed supplies (at least, on our system) a etag for each file which seems to be date & time of the upload. Since you are reading these feeds already, we could just check the etag for each file against the local mtime, and if the modification time is after the etag time, we update the file. If it isn't, we don't. 

I think this should be behind a option-switch for cases where timezones introduce problems. 

I'd try to implement this and create a PR but I wanted to hear some opinions first. Do you see any problems?

**Comment by pfefferf** [comment]
In general I see no issues here. The option switch should switch on/off delta handling. Timezone handling has to be done automatically by the functionality. Also a little research has to be done if the required information is not available in a lower supported release than you are trying it on (to be able to document it).
Thx.

**Comment by pfefferf** [comment]
Closed because of no further response or progress.
