### ISSUE TITLE
404 response (Keine geeignete Ressource gefunden) on upload

### ISSUE THREAD

**Issue by vobujs** [pfefferf/grunt-nwabap-ui5uploader#18]
Hi, 
so I get 
`Warning: Error: got 404 response (Keine geeignete Ressource gefunden) Use --force to continue.`
on the upload try. 
`/sap/bc/adt` is on - so bsp container creation, package association etc all works fine, except the file upload itself.

config:
```
"ABAP"       : {
	"server"      : "https://bla.org",
	"client"      : "100",
	"useStrictSSL": false,
	"ui5"         : {
	  "language"         : "DE",
	  "package"          : "ZYYY",
	  "bspcontainer"     : "ZXXX", 
	  "bspcontainer_text": "some text",
	  "transportno"      : "ABCK900020",
	  "calc_appindex"    : true
	},
	"resources"   : {
	  "cwd": "./deploy/testing",
	  "src": "**/*"
	}
  }
```

grunt verbose output:
```
Running "nwabap_ui5uploader:default" (nwabap_ui5uploader) task
Verifying property nwabap_ui5uploader.default exists in config...OK
File: [no files]
Options: resources={"cwd":"deploy/testing","src":"**/*.*"}, conn={"server":"https://bla.org","client":"100","useStrictSSL":false}, auth={"user":"USR","pwd":"THEPWD"}, ui5={"language":"DE","package":"ZYYY","bspcontainer":"ZXXX","bspcontainer_text":"some text","transportno":"ABCK900020","calc_appindex":true}
Options: <snip - same as above>
Files: Component-preload.js,Component.js,controller/App.controller.js, <snip />
Artifacts to Sync:  [ { type: 'file',
    id: '/Component-preload.js',
    modif: 'update',
    levelCount: 1 },
  { type: 'file',
    id: '/Component.js',
    modif: 'update',
    levelCount: 1 },
  { type: 'file',
    id: '/controller/App.controller.js',
    modif: 'create',
    levelCount: 2 },
  <snip />
  { type: 'folder', id: '/i18n', modif: 'update', levelCount: 1 },
  { type: 'folder', id: '/lib', modif: 'update', levelCount: 1 },
  { type: 'folder', id: '/model', modif: 'update', levelCount: 1 },
  { type: 'folder', id: '/view', modif: 'update', levelCount: 1 } ]
Warning: Error: got 404 response (Keine geeignete Ressource gefunden) Use --force to continue.
```

environment:
macOS 10.13.1
node v8.7.0
grunt-nwabap-ui5uploader-0.2.0

Any idea what causes this? Tried running an ICF trace, but boy, too much ASCII.. :)

**Comment by pfefferf** [comment]
What NW Backend Version (incl. Patch level) you are using?

**Comment by vobujs** [comment]
oh, ja, should have posted that in the first place: 7.50 SP7.
(SAP_BASIS	750	0007	SAPK-75007INSAPBASIS	SAP Basiskomponente)

**Comment by vobujs** [comment]
digging in deeper: upload iva /UI5/UI5_REPOSITORY_LOAD works, same settings for bsp-container, app name and transportno as in the grunt task

**Comment by pfefferf** [comment]
Just tested. For me it works.
Maybe you can make a trace (the ASCII things should'nt be to confusing).

Comparing that thing with the UI5_REPOSITORY_LOAD is not really helpful, cause the thing works a little bit different :).

/sap/bc/adt (+ all sub-pathes) is enough cause all requests are done against /sap/bc/adt/filestore/ui5-bsp/objects.

**Comment by vobujs** [comment]
debugging the grunt task, there seems to be something off in filestore.js:584ff. 
when constructing the REST URI: the encoding of the first "/" looks odd (this corresponds to file "/controller/App.controller.js"):
https://server/sap/bc/adt/filestore/ui5-bsp/objects/ZXXX**%2**Fcontroller/content?type=file&isBinary=false&name=App.controller.js&devclass=%24TMP&charset=UTF-8

**Comment by pfefferf** [comment]
It is a "%2F" (escaped slash), not a "%2". That is necessary that the folder is interpreted correctly. 
What about the blank spaces before and after the %2 in your provided URL. Are they added by you or is that the real generated URL (which I don't think)?

**Comment by vobujs** [comment]
added the spaces for illustration purposes. 
funny thing is that in my environment, the synchronisation for folders works (`FileStore.syncFolder`), for files (`FileStore.syncFile`) it doesn't.
will try different node versions and report back on that.

**Comment by vobujs** [comment]
tried it with 6.12.0, 8.9.1, 9.2.0 - same 404 error.
next: will try with different network access path (currently via VPN) to exclude any reverse-proxy related issues.

**Comment by vobujs** [comment]
**_urgh_** found it: the reverse proxy seems to mess up POST/PUT requests. 
grunt task works fine if target NW system is accessed from the same LAN segments.
Sorry for causing effort here :( Closing this.
But still thanks for your hints!
