### ISSUE TITLE
Add option to use existing transport when 'create_transport' is used

### ISSUE THREAD

**Issue by mxschmitt** [pfefferf/grunt-nwabap-ui5uploader#21]
Hello,

it would be cool to use an existing transport request when the `create_transport` is used. It should be determine to use the existing request when the name of the request match with the given one from the `transport_text` option. Otherwise it should create a new one with the given name.

Best regards

Max

**Comment by pfefferf** [comment]
Validations on texts are always a bad idea. Closed.
