### ISSUE TITLE
Replacing UTF-8 with ISO 8859-1

### ISSUE THREAD

**Issue by mschleeweiss** [pfefferf/grunt-nwabap-ui5uploader#29]
I had the feeling that SAP wanted to move away from ISO 8859-1.

The only reason why `.properties` files had to be ISO 8859-1 was "because that's how it's done in Java". However [this changed with Java 9](http://openjdk.java.net/jeps/226), where `.properties` have to be UTF-8 encoded.

Before updating to `0.2.8` we saved our `.properties` files as UTF-8, we deployed them as UTF-8 and they got served as UTF-8. The world was fine.

After updating to `0.2.8` and changing everything to ISO 8859-1 we now have problems when opening a project in the SAP Web IDE.

The Web IDE likes to keep things simple and stores every file as UTF-8. And this has some obvious side effects: 

![image](https://user-images.githubusercontent.com/2648848/40843974-fe1c1294-65b2-11e8-9df1-518c334f3b7a.png)

So right now it's not possible for use to use the Web IDE and a local IDE like VSCode side by side.

There are issues in other SAP repositories regarding the encoding as well:

SAP/ui5-server#7
SAP/connect-openui5#20

Both more or less suggest dropping ISO 8859-1.

**Comment by pfefferf** [comment]
Fixed with [b9f30a7](https://github.com/pfefferf/grunt-nwabap-ui5uploader/commit/a6877357e07584231a43f80e065d60724526594d).
