### ISSUE TITLE
Loop because of `transport_use_locked`

### ISSUE THREAD

**Issue by themasch** [pfefferf/grunt-nwabap-ui5uploader#30]
So I was running a deployment with this configuration: 
```
            create_transport: true,
            transport_text: 'some clever text',
            transport_use_user_match: true,
            transport_use_locked: true
```

And this is what happend: 
```
NW ABAP UI5 Uploader: Warning: the current BSP Application was already locked in TRN4711. Now we are using transport TRN4711 instead of TRN4711.
NW ABAP UI5 Uploader: Warning: the current BSP Application was already locked in TRN4711. Now we are using transport TRN4711 instead of TRN4711.
NW ABAP UI5 Uploader: Warning: the current BSP Application was already locked in TRN4711. Now we are using transport TRN4711 instead of TRN4711.
NW ABAP UI5 Uploader: Warning: the current BSP Application was already locked in TRN4711. Now we are using transport TRN4711 instead of TRN4711.
.... a lot!
```

The Tansport (I called it TRN4711 in the log above) is the last transport that locked that the BSP but is already closed and transported. 

I'm not really sure on how this should be handled in this case. It should certainly not try to use 'X instead of X'.

**Comment by pfefferf** [comment]
Hi Mark,

unfortunately I cannot reproduce that issue on any of my available backend versions (7.40, 7.5x).

But of course it should not use the same transport number which is identified as already released.

Can you please adjust in file "./tasks/lib/filestore.js" line 699
from
`if (aMatched && aMatched.length > 0) {`
to
`if (aMatched && aMatched.length > 0 && aMatched[0] !== me._oOptions.ui5.transportno) {`
and run it again.

With that no retry will be executed in case the transport no is the same and the original error message/reponse is written to the log. 

Would be greated if you could do that and post the reponse here.

Thx,
Florian

**Comment by themasch** [comment]
I'll check that as soon as I find some time.

**Comment by themasch** [comment]
Okay I can't reproduce it, too. It might have been an issue with this very system. Sorry. 
It currently fails to create a transport, too. But that might, again, be an issue depending on sap servers release. I'll investigate.
