### ISSUE TITLE
Error in uploading .svg file

### ISSUE THREAD

**Issue by promosjotte** [pfefferf/grunt-nwabap-ui5uploader#31]
Hi,

got this message:

`
Warning: Error: got 500 response (<?xml version="1.0" encoding="utf-8"?><exc:exception xmlns:exc="http://www.sap.com/abapxml/types/communicationframework"><namespace id="com.sap.adt"/><type id="ExceptionResourceCreationFailure"/><message lang="EN">Es existiert bereits eine Seite, ein Controller oder ein Mime DEST/RES/EMBED/ASSETS/FONTS/EMOTICONS.SVG in /*NAMESPACE*/*PACKACKAGE*</message><localizedMessage lang="DE">Es existiert bereits eine Seite, ein Controller oder ein Mime DEST/RES/EMBED/ASSETS/FONTS/EMOTICONS.SVG in /*NAMESPACE*/*PACKACKAGE*</localizedMessage><properties/></exc:exception>) Use --force to continue.`

if I try to upload a svg file...

Translated: There is already a Site, Controller or Mime DEST/RES/EMBED/ASSETS/FONTS/EMOTICONS.SVG in the package xy.

**Comment by pfefferf** [comment]
Unfortunately I am not able to reproduce your error. I tried the initial upload and update of an SVG file in different constellations (e.g. $TMP package, transportable package, different BSP apps to check for duplicates Mimes, ...).

Are you able to provide me a  minimized version of your project (just including the SVG of course) which leads to the error on your system. Please add also the information what NW version you are using.

**Comment by pfefferf** [comment]
Not reproduceable, no feedback to asked questions => closed.
