### ISSUE TITLE
Issue with deploying to gateway

### ISSUE THREAD

**Issue by kovboyjder** [pfefferf/grunt-nwabap-ui5uploader#33]
Hi,

First of all, Thanks for this plugin. We are using it to streamline our pipeline build.

However we recently upgraded to the latest version of the repo, but we are getting the following error:
Fatal error: Error: tunneling socket could not be established, statusCode=503

Looking at stackoverflow, it mentions a proxy. But we aren't using a proxy in our setup.

**Comment by pfefferf** [comment]
Can you share the config in your Gruntfile? I just re-checked the sources, but didn't find an issue. When no proxy is set, the proxy logic is ignored and the upload works in my case.

**Comment by kovboyjder** [comment]
This is our config file
`/* global process:true */
"use strict";
module.exports = function (grunt) {
	// Project properties

		if (!process){
			var process = {};
			process.env = {};

			process.env.ABAP_DEVELOPMENT_USER = 'zp001631';
			process.env.ABAP_DEVELOPMENT_PASSWORD = 'Fernand01.';
			process.env.ABAP_DEVELOPMENT_SERVER_HOST = "https://myhr-dev.health.qld.gov.au/";
			process.env.ABAP_APPLICATION_NAME = 'ZHR_PROCESSFLOW';
			process.env.ABAP_APPLICATION_DESC = 'Reuse Process Flow component';
			process.env.ABAP_PACKAGE = 'ZHR_FIORIAPP';
		}
	var webAppDir = "webapp";
	var targetDir = "dist";
	var preloadPrefix = "be/wl/DemoMulitLabels";
	var namespace = "qldh";
	var abapDevelopmentUser = process.env.ABAP_DEVELOPMENT_USER;
	var abapDevelopmentPassword = process.env.ABAP_DEVELOPMENT_PASSWORD;
	var abapDevelopmentServerHost = process.env.ABAP_DEVELOPMENT_SERVER_HOST;
	var abapApplicationName = process.env.ABAP_APPLICATION_NAME;
	var abapApplicationDesc = process.env.ABAP_APPLICATION_DESC;
	var abapPackage = process.env.ABAP_PACKAGE;
	var gitCommit = "EMR"; //process.env.CI_COMMIT_TITLE;
	var resourceroots = {};
	resourceroots[namespace] = './base';
	var preprocessorsWebAppDir = {};
	preprocessorsWebAppDir['{' + webAppDir + ',' + webAppDir + '/!(test)}/*.js'] = ['coverage'];

	var config = {

		jsdoc: {
			dist: {
				src: ["./webapp/*.js", "./webapp/controller/*.js", "./webapp/model/*.js"],
				options: {
					destination: "doc"

				}
			}
		},
		eslint: {
			options: {
				configFile: ".eslintrc.js"
			},
			target: [webAppDir + "/**/*.js"]
		},
		nwabap_ui5uploader: {
			options: {
				conn: {
					server: abapDevelopmentServerHost,
					useStrictSSL: false
				},
				auth: {
					user: abapDevelopmentUser,
					pwd: abapDevelopmentPassword
				}
			},
			upload_build: {
				options: {
					ui5: {
						package: abapPackage,
						bspcontainer: abapApplicationName,
						bspcontainer_text: abapApplicationDesc,
						create_transport: true,
						transport_use_user_match: true,
						transport_text: gitCommit,
						calc_appindex: true
					},
					resources: {
						cwd: targetDir,
						src: "**/*.*"
					}
				}
			}
		},
		clean: {
			dist: 'dist',
			coverage: 'coverage',
			test: 'dist/test',
			localService: 'dist/localService'
		},
		jsdoc2md: {
		 separateOutputFilePerInput: {
			 files: [
				 { src: 'webapp/controller/MovementDetails.controller.js', dest: 'readme/MovementDetails.md' },
				 { src: 'webapp/controller/Wizard.controller.js', dest: 'readme/Wizard.md' },
				 { src: 'webapp/controller/Allowances.controller.js', dest: 'readme/Allowances.md' },
				 { src: 'webapp/controller/App.controller.js', dest: 'readme/App.md' },
				 { src: 'webapp/controller/BaseController.js', dest: 'readme/BaseController.md' },
				 { src: 'webapp/controller/Certifications.controller.js', dest: 'readme/Certifications.md' },
				 { src: 'webapp/controller/EmployeeConditions.controller.js', dest: 'readme/EmployeeConditions.md' },
				 { src: 'webapp/controller/ErrorHandler.js', dest: 'readme/ErrorHandler.md' },
				 { src: 'webapp/controller/NotFound.controller.js', dest: 'readme/NotFound.md' },
				 { src: 'webapp/controller/Other.controller.js', dest: 'readme/Other.md' },
				 { src: 'webapp/controller/PosDetails.controller.js', dest: 'readme/PosDetails.md' },
				 { src: 'webapp/controller/ProcessFlow.controller.js', dest: 'readme/ProcessFlow.md' },
				 { src: 'webapp/controller/Vaccinations.controller.js', dest: 'readme/Vaccinations.md' },
				 { src: 'webapp/controller/WorkSchedule.controller.js', dest: 'readme/WorkSchedule.md' }
			 ]
		 }
	 },
	 pkg: grunt.file.readJSON('package.json'),
  readme_generator: {
    my_generator : { //Thank you @JFusco
      options: {
        // Task-specific options go here.
        // detailed explanation is under options
        // Default options:
        readme_folder: "readme",
        output: "README.md",
        table_of_contents: true,
        toc_extra_links: [],
        generate_changelog: false,
        changelog_folder: "changelogs",
        changelog_version_prefix: null,
        changelog_insert_before: null,
        banner: null,
        has_travis: true,
        github_username: "aponxi",
        travis_branch: "master",
        generate_footer: true,
        generate_title: true,
        package_title: null,
        package_name: null,
        package_desc: null,
        informative: true,
        h1: "#",
        h2: "##",
        back_to_top_custom: null
      },
      order: {
        // Title of the piece and the File name goes here
        // "Filename" : "Title"
        "MovementDetails.md": "MovementDetails",
        "Wizard.md": "Wizard",
				"Allowances.md": "Allowances",
        "App.md": "App",
				"BaseController.md": "BaseController",
        "Certifications.md": "Certifications",
				"EmployeeConditions.md": "EmployeeConditions",
        "ErrorHandler.md": "ErrorHandler",
				"NotFound.md": "NotFound",
        "Other.md": "Other",
				"PosDetails.md": "PosDetails",
				"ProcessFlow.md": "ProcessFlow",
        "Vaccinations.md": "Vaccinations",
				"WorkSchedule.md": "WorkSchedule"
      }
    }
  }
	};
	grunt.loadNpmTasks("grunt-eslint");
	grunt.loadNpmTasks("grunt-nwabap-ui5uploader");
	grunt.loadNpmTasks("@sap/grunt-sapui5-bestpractice-build");
	grunt.loadNpmTasks("grunt-openui5");
	grunt.loadNpmTasks("grunt-jsdoc");
	 grunt.loadNpmTasks('grunt-jsdoc-to-markdown');
	 grunt.loadNpmTasks('grunt-readme-generator');


	grunt.config.merge(config);

	grunt.registerTask("check-lint", "Check validation", function () {
		var validation = grunt.file.readJSON(targetDir + "/di.code-validation.core_issues.json"),
			hasErrors = false;
		for (var check in validation.results) {
			grunt.log.writeln("Result for: " + check);
			for (var file in validation.results[check].issues) {
				validation.results[check].issues[file].forEach(function (error) {
					if (error.severity === "error") {
						grunt.log.error(error.path + "(" + error.line + "," + error.column + ") : " + error.message).error();
						hasErrors = true;
					}
				});
			}
		}
		if (hasErrors) {
			grunt.fail.warn('Errors found during code validation');
		}
	});

	grunt.registerTask("js-doc", "jsdoc");
	//grunt.registerTask('unit-test', ['karma:src']);
	grunt.registerTask("fiori-test", ["lint", "check-lint"]);
	grunt.registerTask('buildapp', ['build', 'clean:test', 'clean:localService']);
	grunt.registerTask('markdown', 'jsdoc2md');
	grunt.registerTask('readme', 'readme_generator');

	grunt.registerTask("deploy", ["nwabap_ui5uploader"]);
	grunt.registerTask("default", [
		"lint",
		"clean",
		"build",
		"jsdoc"
	]);
};
`

**Comment by pfefferf** [comment]
Thx for the file. Looks fine. But unfortunately I do not have a solution for your issue. As said before, the changes introduced in the last version only add the optional option to use a proxy. If no proxy is used, the additional logic is not used. I tested it in an evironment with proxy and without proxy for both http and https, all options/combinations works fine. So I think something has changed in your landscape.

**Comment by pfefferf** [comment]
Not reproducable + no further information anymore => closed.
