### ISSUE TITLE
Transport matcher by bspcontainer

### ISSUE THREAD

**Issue by CarlosOrozco88** [pfefferf/grunt-nwabap-ui5uploader#38]
Hi there,

I have multiple ui5 projects in the same workspace (like 30-40 projects) and 5 developers working on. Each project has their own package, gruntfile, etc. and they are independant from each other in different bsp:

- Workspace
  - Project 1
    - gruntfile.js with nwabap_ui5uploader
  - Project 2
    - gruntfile.js with nwabap_ui5uploader
  - Project N
    - gruntfile.js with nwabap_ui5uploader

When I want to deploy some project, the option "transport_use_user_match" mix all the bsp in one transport.
Is it possible to create an option "transport_bspconainter_match" (user independant)?

I know there is an option "transportno", but it's unconfortable to use with a lot of projects and developers.

Regards,
Carlos

**Comment by pfefferf** [comment]
What would be the difference between the existing option "transport_use_locked" and the new requested option "transport_bspcontainer_match"? In both cases it is required that the specific BSP container is already part of a transport to be able to determine an existing specific transport.
