### ISSUE TITLE
Feature request: Return TR code when `options.ui5.create_transport` is `true`

### ISSUE THREAD

**Issue by mcanalesmayo** [pfefferf/grunt-nwabap-ui5uploader#39]
When `options.ui5.create_transport` is `true`, it would be nice if the new TR code is returned somehow to the caller (maybe by outputting it?). These are some of the scenarios in which it would be helpful:
- Doing another call to the ABAP system to release the previously created TR.
- When there's an integration with other tools (specially project or change management tools such as Service Now or Jira), it may be needed to use this TR code, e.g. for documenting purposes in a change.

**Comment by pfefferf** [comment]
Created transport no is logged now. Please update to version 0.3.4.
