### ISSUE TITLE
Feature request: Provide sap-client id as parameter

### ISSUE THREAD

**Issue by pensoffsky** [pfefferf/grunt-nwabap-ui5uploader#4]
Hi,

currently there is no way to provide the sap-client id in your grunt config. That would be a nice feature so that you don't have to configure the default client id in the system.

Best regards,
Pensoffsky

**Comment by pfefferf** [comment]
Hi,

option 'options.conn.client' added in v0.1.9 to be able to specify a SAP client (transferred as sap-client URL parameter) if no default client is maintained in system.

Best Regards,
Florian
