### ISSUE TITLE
Proxy with authentication

### ISSUE THREAD

**Issue by MatthieuLeMee** [pfefferf/grunt-nwabap-ui5uploader#40]
Thank you for this useful plugin !

How can we use grunt-nwabap-ui5uploader behind a proxy WITH authentication ?
I cannot find any info to set username/password for the proxy used to upload the bsp app using /adt api.

**Comment by pfefferf** [comment]
The plugin uses the [request](https://github.com/request/request) node module. It supports proxy basic authentication like described in the documentation of that module:

> proxy - an HTTP proxy to be used. Supports proxy Auth with Basic Auth, identical to support for the url parameter (by embedding the auth info in the uri)
