### ISSUE TITLE
Redeploy and overwrite existing application

### ISSUE THREAD

**Issue by Steve192** [pfefferf/grunt-nwabap-ui5uploader#41]
Hi,

I wanted to redeploy a newer version of my application and was expecting the uploader to simply overwrite the old one:

Warning: <?xml version="1.0" encoding="utf-8"?><exc:exception xmlns:exc="http://www.sap.com/abapxml/types/communicationframework"><namespace id="com.sap.adt"/><type id="ExceptionResourceCreationFailure"/><message lang="EN">Page, controller, or MIME xxxx.JS already exists in application xxxxx</message><localizedMessage lang="EN">Page, controller, or MIME xxxxx.JS already exists in application xxxxx</localizedMessage><properties/></exc:exception> Use --force to continue.

It works for regular pages "Pages with Flow Logic", but not for mime objects (e.g. Pictures, Other javascript libraries etc.)

How do you handle redeploying and overwriting such existing applications?

**Comment by pfefferf** [comment]
Can you share your project?

**Comment by Steve192** [comment]
My application is not a regular ui5 application, but a compiled react app (should not make a difference since ui5 is also just html / javascript?).

Is consists of 2 files which need to be uploaded:
![image](https://user-images.githubusercontent.com/6454983/62109350-62031900-b2ac-11e9-9e54-12da7e0506df.png)

This is my grunt config:
```
const webpackConfigDev = require('./config/webpack.dev.js');
const webpackConfigProd = require('./config/webpack.prod.js');

module.exports = function (grunt) {
    var sUser = grunt.option('sap_user');
    var sPwd = grunt.option('sap_password');
    // Project configuration.
    grunt.initConfig({
        webpack: {
            prod: webpackConfigProd,
        },
        nwabap_ui5uploader: {
            options: {
                conn: {
                    server: 'http://server:80',
                },
                auth: {
                    user: sUser,
                    pwd: sPwd
                }
            },
            upload_build: {
                options: {
                    ui5: {
                        package: 'ZPACKAGE',
                        bspcontainer: 'ZBSPPAGE',
                        bspcontainer_text: 'Description',
                        create_transport: true,
                        transport_use_user_match: true,
                        transport_text: 'Transport for xxx container'
                    },
                    resources: {
                        cwd: 'dist',
                        src: '**/*.*'
                    }
                }
            }
        }
    });

    grunt.loadNpmTasks('grunt-webpack');
    grunt.loadNpmTasks('grunt-nwabap-ui5uploader');
};
```

**Comment by Steve192** [comment]
In the meantime I "fixed" the issue by simply deleting main.bundle.js in the BSP repository. After this, updating works fine, even if the file exists. Strange ..

```
Running "nwabap_ui5uploader:upload_build" (nwabap_ui5uploader) task
NW ABAP UI5 Uploader: file /index.html updated.
NW ABAP UI5 Uploader: file /main.bundle.js updated.

Done.
```
