### ISSUE TITLE
Transport creation enhancement

### ISSUE THREAD

**Issue by DenisTis** [pfefferf/grunt-nwabap-ui5uploader#43]
Hi Florian,

thanks a lot for a great tool!
Could you please enhance transport creation option?
I assumed that when you use "transport creation with user match", it would check all open transports of given user searching for the same transport text, as provided in grunt task configuration.
However, it just picks up first opened transport of the user.

Could you please enhance it?

**Comment by pfefferf** [comment]
Determination functionality works as designed -> no enhancement regarding text comparison will be done.
