### ISSUE TITLE
upload of mime files

### ISSUE THREAD

**Issue by schealex** [pfefferf/grunt-nwabap-ui5uploader#45]
Hello,

i'm using this to upload a react app to our backend. the upload is working fine but the *.js and *.css files cannot be loaded from the index.html:

Refused to apply style from 'https://XXX/static/css/main.36497136.chunk.css' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.
5index.html:12 GET https://XXX/static/js/2.75b9e5ec.chunk.js net::ERR_ABORTED 404

if i manually upload the files to the MIMEs category within the BSP it works.
is there any way to fix this?

Regards
Alex

**Comment by pfefferf** [comment]
Any example you can share for reproduction?

**Comment by schealex** [comment]
i've made you a sample project from the official sap demo app

https://github.com/schealex/ui5-webcomponents-sample-react

steps to reproduce:

1. npm i
2. npm run build
3. grunt -user=x -pwd=x -server=x -package=x -container=x -transp=x

you will find that only the *.ico and *.png will be in the MIME category not the *.css and *.js files which would be a must.

**Comment by pfefferf** [comment]
Checked that issue. Following I found out:
- For the CSS file I got the error "File contains different line feeds. Mixed line feeds are not supported" -> after fixing that "mixed line feed" issue, I was able to upload that file.
- All JS files could be uploaded, expect for the "runtime\~main.xxxx.js" file. For that it was indicated that it was successfully uploaded, but because of a not allowed special sign ("~"), the upload failed. I corrected the error handling for that with version 1.0.2 of the plugin (it is crazy that the service returns a 403 in case of that error). When I have changed the file to a valid name (I removed the ~ sign), then I could upload the file. I adapted the file name too in the index.html file. After that the application is working when served on an ABAP system.
![image](https://user-images.githubusercontent.com/9888617/73049752-b95dfc80-3e7d-11ea-96f9-7699503041ec.png)

Regarding MIME-Types all the issues are not relevant.

**Comment by schealex** [comment]
i'm not exactly sure what you're saying but i have had no problems with the files being uploaded. The upload works for me but the files are not accessable from the app because they are not in the right bsp category? Or am i missing something?
Also when you are saying "after fixing that "mixed line feed" issue, I was able to upload that file" what do you mean by that?

**Comment by pfefferf** [comment]
The files are stored at the correct place with correct category in the BSP app.
Regarding the 2nd point -> please the the internet for that, I will not explain things again which are described already several thousand times ;-)

As I do not know your concrete environment setup I cannot say anymore. I can just say, after resolving the above described issues the app was working served on an ABAP system (tried it with an old 7.40 system and a new 1909 system).

**Comment by schealex** [comment]
i think we are talking about different things.
This is what i have in our system after uploading with the plugin:

<img width="465" alt="saplogon_D8uankdX7l" src="https://user-images.githubusercontent.com/3441348/73065418-cc83c300-3ea3-11ea-9290-bbe4af968a96.png">

as you can see only the icon and image are below the MIMEs category. Therefore when i open the index file i get the errors stated in OP. :/

**Comment by pfefferf** [comment]
I understood you already the first time, but I cannot reproduce your "issue". But again I do not see any reason why the files must be stored in the MIME repository.

That's what I get:
![image](https://user-images.githubusercontent.com/9888617/73067238-69e0f600-3ea8-11ea-903c-551cffa2ebd0.png)

Loading works fine:
![image](https://user-images.githubusercontent.com/9888617/73067300-998ffe00-3ea8-11ea-98e8-62ed8a19d697.png)

I did another test. Deploying your test app via the Web IDE to the ABAP backend. And here I get the exact same result (except the Che Information of the Web IDE) like the deployer produces (and it runs too):
![image](https://user-images.githubusercontent.com/9888617/73067400-dfe55d00-3ea8-11ea-9f1f-1c6a65056ea6.png)

So at the moment I do not see any reason what your issue has to do with the uploader.

Why you do not have the upload problems? I don't know. I just tried to deploy the stuff created by the build script. And that produces that from an BSP repository point of view corrupted stuff.

**Comment by schealex** [comment]
very strange, i'll investigate on the server side. i was under the impression that maybe the upload "category" of those files is wrong or whatever.
anyways thanks for your effort. I'll post an update if i manage to find the issue. Maybe someone else runs into the same problem.

Regards
Alex

**Comment by pfefferf** [comment]
ok, thx.

bye the way, just saw that we are working for the same group ;-); if necessary we can arrange a call
