### ISSUE TITLE
Component-preload.js gets renamed after uploading

### ISSUE THREAD

**Issue by amit1agrawal** [pfefferf/grunt-nwabap-ui5uploader#9]
Hi,
I used grunt-openui5 plugin to  build Component-preload for my project. After that I used this plugin to upload only the Component-preload to NW GW server. However, after uploading the file is getting renamed into something unrecognizable like UI5B2B5D24.......
In order to check whether it's an issue with plugin or the report /UI5/UI5_REPOSITORY_LOAD, I upload the same project using the report. There again, Component-preload.js got renamed to something cryptic (basically a GUID).
So this is exactly not an issue with this plugin but there must be some reason the report is not allowing Component-preload.js and I wanted to know whether this scenario is handled by the plugin in some way. Basically, How can I use this plugin along with grunt-openui5 to upload Component-preload file to NW GW server? If possible please do provide such an option in this plugin.

**Comment by pfefferf** [comment]
What NW Version and SPS level you are using?

**Comment by amit1agrawal** [comment]
NW Version is 7.40 SP14. SAP_GWFND component is at SP15.

**Comment by pfefferf** [comment]
Did some checks. From my point of view all is correct. It seems that for the Component-preload.js file a kind of internal mapping is done (for whatever reason, maybe you can ask your SAP colleagues). The file is returned if you call the app in the browser (check e.g. via network tab in dev tools). Also the /UI5/UI5_REPOSITORY_LOAD report can map that GUID like filename to the original name, when the application is downloaded.

Regards,
Florian

**Comment by amit1agrawal** [comment]
Hi Florian,
Thanks for your inputs.
I just verified what you said. I was suspecting that Component-preload.js is built by /UI5/UI5_REPOSITORY_LOAD but that is not the case, though it would have been nice if that was also included.
The Component-preload.js does gets served when application is loaded.

Regards,
Amit
